version: 2

project_name: slack-chat-cli

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: slck
    main: ./cmd/slck
    binary: slck
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/open-cli-collective/slack-chat-api/internal/version.Version={{.Version}}
      - -X github.com/open-cli-collective/slack-chat-api/internal/version.Commit={{.Commit}}
      - -X github.com/open-cli-collective/slack-chat-api/internal/version.Date={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    # Use binary name with v prefix for archive filenames
    name_template: "slck_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Other
      order: 999
